### ISSUE TITLE
How to link and use architecture dispatch?

### ISSUE THREAD

**Issue by chriselrod** [google/highway#1005] opened 2022-10-01 20:36 UTC
I tried a minimal example below, but it did not seem to work:
```
> gcc -O3 -march=native -Ihighway highwaytest.cpp -o highwaytestnativegcc
> gcc -O3 -Ihighway highwaytest.cpp -o highwaytestgcc
> clang -O3 -march=native -Ihighway highwaytest.cpp -o highwaytestnative
> clang -O3 -Ihighway highwaytest.cpp -o highwaytest
> ./highwaytestnativegcc
Test the number of Lane: 8
Lane: 8
2 6 12 20 30 42 56 72 ⏎
chriselrod@fedora ~/D/p/c/simd> ./highwaytestnative
Test the number of Lane: 8
Lane: 8
2 6 12 20 30 42 56 72 ⏎
chriselrod@fedora ~/D/p/c/simd> ./highwaytestgcc
Test the number of Lane: 1
Lane: 1
2 6 12 20 30 42 56 72 ⏎
chriselrod@fedora ~/D/p/c/simd> ./highwaytest
Test the number of Lane: 2
Lane: 2
2 6 12 20 30 42 56 72 ⏎
```
That is, `-march=native` allows for using a full vector width, but we use the minimum width otherwise.

The test script:
```c++
#include <cstdint>
// #include <iostream>
#undef HWY_TARGET_INCLUDE
// #define HWY_TARGET_INCLUDE "vmulinttest.cpp"  // this file
#define HWY_TARGET_INCLUDE                                                     \
  "/home/chriselrod/Documents/progwork/cxx/simd/highwaytest.cpp"
#include <hwy/foreach_target.h> // must come before highway.h
#include <hwy/highway.h>

HWY_BEFORE_NAMESPACE(); // required if not using HWY_ATTR
namespace project {
namespace HWY_NAMESPACE { // required: unique per target

// Can skip hn:: prefixes if already inside hwy::HWY_NAMESPACE.
namespace hn = hwy::HWY_NAMESPACE;

using T = int64_t;

void MulAddLoop(const T *HWY_RESTRICT mul_array,
                const T *HWY_RESTRICT add_array, const size_t size,
                T *HWY_RESTRICT x_array) {
  const hn::ScalableTag<T> d;
  size_t Lane = hn::Lanes(hn::ScalableTag<T>());

  printf("Test the number of Lane: %lu \n", hn::MaxLanes(d));
  printf("Lane: %lu \n", Lane);
  for (size_t i = 0; i < size; i += hn::Lanes(d)) {
    const auto mul = hn::Load(d, mul_array + i);
    const auto add = hn::Load(d, add_array + i);
    auto x = hn::Load(d, x_array + i);
    x = mul * x + add;
    hn::Store(x, d, x_array + i);
  }
}

} // namespace HWY_NAMESPACE
} // namespace project
HWY_AFTER_NAMESPACE();

#if HWY_ONCE
using project::HWY_NAMESPACE::MulAddLoop;
int main() {
  using T = int64_t;

  const T in[8] = {1, 2, 3, 4, 5, 6, 7, 8};
  const T in2[8] = {1, 2, 3, 4, 5, 6, 7, 8};
  T in3[8] = {1, 2, 3, 4, 5, 6, 7, 8};
  MulAddLoop(in, in2, 8, in3);
  for (int i = 0; i < 8; i++) {
    printf("%lu ", in3[i]);
  }
  return 0;
}
#endif
```

Note that the assembly still shows multiple versions, using both ymm and zmm registers:
```asm
	.file	"highwaytest.cpp"
	.intel_syntax noprefix
	.text
	.section	.rodata.str1.8,"aMS",@progbits,1
	.align 8
.LC0:
	.string	"Test the number of Lane: %lu \n"
	.section	.rodata.str1.1,"aMS",@progbits,1
.LC1:
	.string	"Lane: %lu \n"
	.text
	.p2align 4
	.globl	_ZN7project7N_SSSE310MulAddLoopEPKlS2_mPl
	.type	_ZN7project7N_SSSE310MulAddLoopEPKlS2_mPl, @function
_ZN7project7N_SSSE310MulAddLoopEPKlS2_mPl:
.LFB3254:
	.cfi_startproc
	push	r13
	.cfi_def_cfa_offset 16
	.cfi_offset 13, -16
	xor	eax, eax
	mov	r13, rsi
	mov	esi, 2
	push	r12
	.cfi_def_cfa_offset 24
	.cfi_offset 12, -24
	mov	r12, rdi
	mov	edi, OFFSET FLAT:.LC0
	push	rbp
	.cfi_def_cfa_offset 32
	.cfi_offset 6, -32
	mov	rbp, rdx
	push	rbx
	.cfi_def_cfa_offset 40
	.cfi_offset 3, -40
	mov	rbx, rcx
	sub	rsp, 8
	.cfi_def_cfa_offset 48
	call	printf
	xor	eax, eax
	mov	esi, 2
	mov	edi, OFFSET FLAT:.LC1
	call	printf
	test	rbp, rbp
	je	.L1
	xor	eax, eax
	.p2align 4,,10
	.p2align 3
.L3:
	movdqa	xmm3, XMMWORD PTR [rbx+rax*8]
	movdqa	xmm1, XMMWORD PTR [r12+rax*8]
	movdqa	xmm0, xmm3
	movdqa	xmm2, xmm1
	psrlq	xmm0, 32
	pmuludq	xmm2, xmm3
	pmuludq	xmm0, xmm1
	psrlq	xmm1, 32
	pmuludq	xmm1, xmm3
	paddd	xmm0, xmm1
	psllq	xmm0, 32
	paddd	xmm0, xmm2
	paddq	xmm0, XMMWORD PTR [r13+0+rax*8]
	movaps	XMMWORD PTR [rbx+rax*8], xmm0
	add	rax, 2
	cmp	rax, rbp
	jb	.L3
.L1:
	add	rsp, 8
	.cfi_def_cfa_offset 40
	pop	rbx
	.cfi_def_cfa_offset 32
	pop	rbp
	.cfi_def_cfa_offset 24
	pop	r12
	.cfi_def_cfa_offset 16
	pop	r13
	.cfi_def_cfa_offset 8
	ret
	.cfi_endproc
.LFE3254:
	.size	_ZN7project7N_SSSE310MulAddLoopEPKlS2_mPl, .-_ZN7project7N_SSSE310MulAddLoopEPKlS2_mPl
	.p2align 4
	.globl	_ZN7project6N_SSE410MulAddLoopEPKlS2_mPl
	.type	_ZN7project6N_SSE410MulAddLoopEPKlS2_mPl, @function
_ZN7project6N_SSE410MulAddLoopEPKlS2_mPl:
.LFB4015:
	.cfi_startproc
	push	r13
	.cfi_def_cfa_offset 16
	.cfi_offset 13, -16
	xor	eax, eax
	mov	r13, rsi
	mov	esi, 2
	push	r12
	.cfi_def_cfa_offset 24
	.cfi_offset 12, -24
	mov	r12, rdi
	mov	edi, OFFSET FLAT:.LC0
	push	rbp
	.cfi_def_cfa_offset 32
	.cfi_offset 6, -32
	mov	rbp, rdx
	push	rbx
	.cfi_def_cfa_offset 40
	.cfi_offset 3, -40
	mov	rbx, rcx
	sub	rsp, 8
	.cfi_def_cfa_offset 48
	call	printf
	xor	eax, eax
	mov	esi, 2
	mov	edi, OFFSET FLAT:.LC1
	call	printf
	test	rbp, rbp
	je	.L10
	xor	eax, eax
	.p2align 4,,10
	.p2align 3
.L12:
	movdqa	xmm3, XMMWORD PTR [rbx+rax*8]
	movdqa	xmm1, XMMWORD PTR [r12+rax*8]
	movdqa	xmm0, xmm3
	movdqa	xmm2, xmm1
	psrlq	xmm0, 32
	pmuludq	xmm2, xmm3
	pmuludq	xmm0, xmm1
	psrlq	xmm1, 32
	pmuludq	xmm1, xmm3
	paddd	xmm0, xmm1
	psllq	xmm0, 32
	paddd	xmm0, xmm2
	paddq	xmm0, XMMWORD PTR [r13+0+rax*8]
	movaps	XMMWORD PTR [rbx+rax*8], xmm0
	add	rax, 2
	cmp	rax, rbp
	jb	.L12
.L10:
	add	rsp, 8
	.cfi_def_cfa_offset 40
	pop	rbx
	.cfi_def_cfa_offset 32
	pop	rbp
	.cfi_def_cfa_offset 24
	pop	r12
	.cfi_def_cfa_offset 16
	pop	r13
	.cfi_def_cfa_offset 8
	ret
	.cfi_endproc
.LFE4015:
	.size	_ZN7project6N_SSE410MulAddLoopEPKlS2_mPl, .-_ZN7project6N_SSE410MulAddLoopEPKlS2_mPl
	.p2align 4
	.globl	_ZN7project6N_AVX210MulAddLoopEPKlS2_mPl
	.type	_ZN7project6N_AVX210MulAddLoopEPKlS2_mPl, @function
_ZN7project6N_AVX210MulAddLoopEPKlS2_mPl:
.LFB10990:
	.cfi_startproc
	push	rbp
	.cfi_def_cfa_offset 16
	.cfi_offset 6, -16
	xor	eax, eax
	mov	rbp, rsp
	.cfi_def_cfa_register 6
	push	r14
	.cfi_offset 14, -24
	mov	r14, rsi
	mov	esi, 4
	push	r13
	.cfi_offset 13, -32
	mov	r13, rdi
	mov	edi, OFFSET FLAT:.LC0
	push	r12
	.cfi_offset 12, -40
	mov	r12, rdx
	push	rbx
	.cfi_offset 3, -48
	mov	rbx, rcx
	and	rsp, -32
	call	printf
	xor	eax, eax
	mov	esi, 4
	mov	edi, OFFSET FLAT:.LC1
	call	printf
	test	r12, r12
	je	.L26
	xor	eax, eax
	.p2align 4,,10
	.p2align 3
.L21:
	vmovdqa	ymm3, YMMWORD PTR [rbx+rax*8]
	vmovdqa	ymm1, YMMWORD PTR [r13+0+rax*8]
	vpsrlq	ymm0, ymm3, 32
	vpmuludq	ymm2, ymm1, ymm3
	vpmuludq	ymm0, ymm1, ymm0
	vpsrlq	ymm1, ymm1, 32
	vpmuludq	ymm1, ymm1, ymm3
	vpaddd	ymm0, ymm0, ymm1
	vpsllq	ymm0, ymm0, 32
	vpaddd	ymm0, ymm2, ymm0
	vpaddq	ymm0, ymm0, YMMWORD PTR [r14+rax*8]
	vmovdqa	YMMWORD PTR [rbx+rax*8], ymm0
	add	rax, 4
	cmp	rax, r12
	jb	.L21
	vzeroupper
.L26:
	lea	rsp, [rbp-32]
	pop	rbx
	pop	r12
	pop	r13
	pop	r14
	pop	rbp
	.cfi_def_cfa 7, 8
	ret
	.cfi_endproc
.LFE10990:
	.size	_ZN7project6N_AVX210MulAddLoopEPKlS2_mPl, .-_ZN7project6N_AVX210MulAddLoopEPKlS2_mPl
	.p2align 4
	.globl	_ZN7project6N_AVX310MulAddLoopEPKlS2_mPl
	.type	_ZN7project6N_AVX310MulAddLoopEPKlS2_mPl, @function
_ZN7project6N_AVX310MulAddLoopEPKlS2_mPl:
.LFB12925:
	.cfi_startproc
	push	rbp
	.cfi_def_cfa_offset 16
	.cfi_offset 6, -16
	xor	eax, eax
	mov	rbp, rsp
	.cfi_def_cfa_register 6
	push	r14
	.cfi_offset 14, -24
	mov	r14, rsi
	mov	esi, 8
	push	r13
	.cfi_offset 13, -32
	mov	r13, rdi
	mov	edi, OFFSET FLAT:.LC0
	push	r12
	.cfi_offset 12, -40
	mov	r12, rdx
	push	rbx
	.cfi_offset 3, -48
	mov	rbx, rcx
	and	rsp, -64
	call	printf
	xor	eax, eax
	mov	esi, 8
	mov	edi, OFFSET FLAT:.LC1
	call	printf
	test	r12, r12
	je	.L36
	xor	eax, eax
	.p2align 4,,10
	.p2align 3
.L31:
	vmovdqa64	zmm1, ZMMWORD PTR [r13+0+rax*8]
	vpmullq	zmm0, zmm1, ZMMWORD PTR [rbx+rax*8]
	vpaddq	zmm0, zmm0, ZMMWORD PTR [r14+rax*8]
	vmovdqa64	ZMMWORD PTR [rbx+rax*8], zmm0
	add	rax, 8
	cmp	rax, r12
	jb	.L31
	vzeroupper
.L36:
	lea	rsp, [rbp-32]
	pop	rbx
	pop	r12
	pop	r13
	pop	r14
	pop	rbp
	.cfi_def_cfa 7, 8
	ret
	.cfi_endproc
.LFE12925:
	.size	_ZN7project6N_AVX310MulAddLoopEPKlS2_mPl, .-_ZN7project6N_AVX310MulAddLoopEPKlS2_mPl
	.p2align 4
	.globl	_ZN7project8N_SCALAR10MulAddLoopEPKlS2_mPl
	.type	_ZN7project8N_SCALAR10MulAddLoopEPKlS2_mPl, @function
_ZN7project8N_SCALAR10MulAddLoopEPKlS2_mPl:
.LFB13160:
	.cfi_startproc
	push	r13
	.cfi_def_cfa_offset 16
	.cfi_offset 13, -16
	xor	eax, eax
	mov	r13, rdi
	mov	edi, OFFSET FLAT:.LC0
	push	r12
	.cfi_def_cfa_offset 24
	.cfi_offset 12, -24
	mov	r12, rsi
	mov	esi, 1
	push	rbp
	.cfi_def_cfa_offset 32
	.cfi_offset 6, -32
	mov	rbp, rcx
	push	rbx
	.cfi_def_cfa_offset 40
	.cfi_offset 3, -40
	mov	rbx, rdx
	sub	rsp, 8
	.cfi_def_cfa_offset 48
	call	printf
	xor	eax, eax
	mov	esi, 1
	mov	edi, OFFSET FLAT:.LC1
	call	printf
	test	rbx, rbx
	je	.L39
	cmp	rbx, 1
	je	.L44
	mov	rdx, rbx
	xor	eax, eax
	shr	rdx
	sal	rdx, 4
	.p2align 4,,10
	.p2align 3
.L42:
	movdqu	xmm4, XMMWORD PTR [rbp+0+rax]
	movdqu	xmm3, XMMWORD PTR [r13+0+rax]
	movdqu	xmm5, XMMWORD PTR [r12+rax]
	movdqa	xmm0, xmm3
	movdqa	xmm2, xmm4
	movdqa	xmm1, xmm3
	psrlq	xmm0, 32
	psrlq	xmm2, 32
	pmuludq	xmm0, xmm4
	pmuludq	xmm2, xmm3
	pmuludq	xmm1, xmm4
	paddq	xmm0, xmm2
	psllq	xmm0, 32
	paddq	xmm0, xmm1
	paddq	xmm0, xmm5
	movups	XMMWORD PTR [rbp+0+rax], xmm0
	add	rax, 16
	cmp	rdx, rax
	jne	.L42
	test	bl, 1
	je	.L39
	and	rbx, -2
	mov	rdx, rbx
.L41:
	lea	rcx, [rbp+0+rdx*8]
	mov	rax, QWORD PTR [r13+0+rdx*8]
	imul	rax, QWORD PTR [rcx]
	add	rax, QWORD PTR [r12+rdx*8]
	mov	QWORD PTR [rcx], rax
.L39:
	add	rsp, 8
	.cfi_remember_state
	.cfi_def_cfa_offset 40
	pop	rbx
	.cfi_def_cfa_offset 32
	pop	rbp
	.cfi_def_cfa_offset 24
	pop	r12
	.cfi_def_cfa_offset 16
	pop	r13
	.cfi_def_cfa_offset 8
	ret
.L44:
	.cfi_restore_state
	xor	edx, edx
	jmp	.L41
	.cfi_endproc
.LFE13160:
	.size	_ZN7project8N_SCALAR10MulAddLoopEPKlS2_mPl, .-_ZN7project8N_SCALAR10MulAddLoopEPKlS2_mPl
	.section	.rodata.str1.1
.LC6:
	.string	"%lu "
	.section	.text.startup,"ax",@progbits
	.p2align 4
	.globl	main
	.type	main, @function
main:
.LFB13162:
	.cfi_startproc
	push	rbp
	.cfi_def_cfa_offset 16
	.cfi_offset 6, -16
	mov	edx, 8
	push	rbx
	.cfi_def_cfa_offset 24
	.cfi_offset 3, -24
	sub	rsp, 200
	.cfi_def_cfa_offset 224
	movdqa	xmm3, XMMWORD PTR .LC2[rip]
	movdqa	xmm2, XMMWORD PTR .LC3[rip]
	movdqa	xmm1, XMMWORD PTR .LC4[rip]
	movdqa	xmm0, XMMWORD PTR .LC5[rip]
	lea	rsi, [rsp+64]
	mov	rdi, rsp
	lea	rcx, [rsp+128]
	movaps	XMMWORD PTR [rsp], xmm3
	lea	rbx, [rsp+128]
	movaps	XMMWORD PTR [rsp+16], xmm2
	lea	rbp, [rsp+192]
	movaps	XMMWORD PTR [rsp+32], xmm1
	movaps	XMMWORD PTR [rsp+48], xmm0
	movaps	XMMWORD PTR [rsp+64], xmm3
	movaps	XMMWORD PTR [rsp+80], xmm2
	movaps	XMMWORD PTR [rsp+96], xmm1
	movaps	XMMWORD PTR [rsp+112], xmm0
	movaps	XMMWORD PTR [rsp+128], xmm3
	movaps	XMMWORD PTR [rsp+144], xmm2
	movaps	XMMWORD PTR [rsp+160], xmm1
	movaps	XMMWORD PTR [rsp+176], xmm0
	call	_ZN7project8N_SCALAR10MulAddLoopEPKlS2_mPl
	.p2align 4,,10
	.p2align 3
.L55:
	mov	rsi, QWORD PTR [rbx]
	mov	edi, OFFSET FLAT:.LC6
	xor	eax, eax
	add	rbx, 8
	call	printf
	cmp	rbp, rbx
	jne	.L55
	add	rsp, 200
	.cfi_def_cfa_offset 24
	xor	eax, eax
	pop	rbx
	.cfi_def_cfa_offset 16
	pop	rbp
	.cfi_def_cfa_offset 8
	ret
	.cfi_endproc
.LFE13162:
	.size	main, .-main
	.section	.rodata.cst16,"aM",@progbits,16
	.align 16
.LC2:
	.quad	1
	.quad	2
	.align 16
.LC3:
	.quad	3
	.quad	4
	.align 16
.LC4:
	.quad	5
	.quad	6
	.align 16
.LC5:
	.quad	7
	.quad	8
	.ident	"GCC: (GNU) 12.2.1 20220819 (Red Hat 12.2.1-2)"
	.section	.note.GNU-stack,"",@progbits
```
so the failure seems to be in dispatch, not in code generation.
That is, it seems to be generating code for each target, but dispatch always seems to select the minimal version, rather than an appropriate version as would be compiled with `-march=native`.

My CPU is Intel Tiger lake.

Looking at the assembly, the `main` function has a direct call to `_ZN7project8N_SCALAR10MulAddLoopEPKlS2_mPl`, i.e. the SCALAR target.
Is `main` located in the wrong location, does it need some macro, or?
How is the versioning dispatch supposed to be handled?

**Comment by chriselrod** [comment] 2022-10-01 20:55
Just found https://github.com/google/highway/blob/master/hwy/examples/skeleton.cc
I'll try and follow that example.

**Comment by chriselrod** [comment] 2022-10-01 21:46
Currently, I have
```c++
#include <hwy/base.h>
// Generates code for every target that this compiler can support.
#include <cstdint>
// #include <iostream>
#undef HWY_TARGET_INCLUDE
// #define HWY_TARGET_INCLUDE "vmulinttest.cpp"  // this file
#define HWY_TARGET_INCLUDE                                                     \
  "/home/chriselrod/Documents/progwork/cxx/simd/highwaytest.cpp"
#include <hwy/foreach_target.h> // must come before highway.h
#include <hwy/highway.h>


HWY_BEFORE_NAMESPACE(); // required if not using HWY_ATTR
namespace project {
namespace HWY_NAMESPACE { // required: unique per target

// Can skip hn:: prefixes if already inside hwy::HWY_NAMESPACE.
namespace hn = hwy::HWY_NAMESPACE;

using T = int64_t;

void MulAddLoop(const T *HWY_RESTRICT mul_array,
                const T *HWY_RESTRICT add_array, const size_t size,
                T *HWY_RESTRICT x_array) {
  const hn::ScalableTag<T> d;
  size_t Lane = hn::Lanes(hn::ScalableTag<T>());

  printf("Test the number of Lane: %lu \n", hn::MaxLanes(d));
  printf("Lane: %lu \n", Lane);
  for (size_t i = 0; i < size; i += hn::Lanes(d)) {
    const auto mul = hn::Load(d, mul_array + i);
    const auto add = hn::Load(d, add_array + i);
    auto x = hn::Load(d, x_array + i);
    x = mul * x + add;
    hn::Store(x, d, x_array + i);
  }
}

} // namespace HWY_NAMESPACE
} // namespace project
HWY_AFTER_NAMESPACE();

#if HWY_ONCE
namespace project {
HWY_EXPORT(MulAddLoop);
// using project::HWY_NAMESPACE::MulAddLoop;
HWY_DLLEXPORT int main() {
  using T = int64_t;

  const T in[8] = {1, 2, 3, 4, 5, 6, 7, 8};
  const T in2[8] = {1, 2, 3, 4, 5, 6, 7, 8};
  T in3[8] = {1, 2, 3, 4, 5, 6, 7, 8};
  HWY_DYNAMIC_DISPATCH(MulAddLoop)(in, in2, 8, in3);
  for (int i = 0; i < 8; i++) {
    printf("%lu ", in3[i]);
  }
  return 0;
}
} // namespace project
int main() { return project::main(); }
#endif
```
but I don't know how to link it.
```
> clang -O3 -Ihighway -lhwy highwaytest.cpp -o highwaytest
/usr/bin/ld: /tmp/highwaytest-954e0f.o: in function `project::main()':
highwaytest.cpp:(.text+0x4dc): undefined reference to `hwy::GetChosenTarget()'
/usr/bin/ld: /tmp/highwaytest-954e0f.o: in function `_ZN3hwy13FunctionCacheIvJPKlS2_mPlEE13ChooseAndCallIXadsoKPFvS2_S2_mS3_EL_ZN7projectL30MulAddLoopHighwayDispatchTableEEEEEEvS2_S2_mS3_':
highwaytest.cpp:(.text+0x5c6): undefined reference to `hwy::GetChosenTarget()'
/usr/bin/ld: highwaytest.cpp:(.text+0x5ce): undefined reference to `hwy::SupportedTargets()'
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jan-wassenberg** [comment] 2022-10-03 07:57
Your code should use LoadU instead of Load because the arrays are not guaranteed to be aligned.
Otherwise, it looks fine. No further action in your code is required for runtime dispatch.

But: in the compile flags, you probably do not want to mix -march= and runtime dispatch. No extra compile flags are required.

For linking, are you able to use CMake? If so, the following is sufficient:
`target_link_libraries(your_target hwy)`

It is possible our CPU detection may have a bug triggered by Tiger Lake. Can you printf the value of `targets` at the end of SupportedTargets in targets.cc?

**Comment by JunpengGao233** [comment] 2022-10-06 21:29
Hi, I also got the same error by running that code and implement my own model.

My cpu is Intel Core i7-12650H based on the Alder Lake architecture. I add printf `targets` at the end of SupportedTagets in targets.cc and run benchmark.cc. It returns

```
targets: 6917529027641088512
targets: 512

F(x)->2*x^2, F(3) = 18.0
------------------------ AVX2
       dot:   3456:  0.081 (+/- 0.001)
     delta:   3456:  0.185 (+/- 0.001)
targets: 2048

F(x)->2*x^2, F(3) = 18.0
------------------------ SSE4
       dot:   3456:  0.153 (+/- 0.002)
     delta:   3456:  0.362 (+/- 0.001)
targets: 4096

F(x)->2*x^2, F(3) = 18.0
------------------------ SSSE3
       dot:   3456:  0.153 (+/- 0.002)
     delta:   3456:  0.304 (+/- 0.001)
targets: 4611686018427387904

F(x)->2*x^2, F(3) = 18.0
------------------------ SCALAR
       dot:   3456:  0.605 (+/- 0.003)
     delta:   3456:  0.720 (+/- 0.001)
targets: 6917529027641088512
```

**Comment by jan-wassenberg** [comment] 2022-10-07 08:06
Hi @JunpengGao233, thanks for adding the printf. The first number is missing 0x100 = HWY_AVX3, but this is expected on Alder Lake (support for AVX-512 was removed from them). Unless you got one of the early ones where AVX-512 still work(ed)?

For the macro name error, it seems to be coming from the command line. Do you have any `-D` arguments to the compiler? If not, can you share the command line used?

**Comment by JunpengGao233** [comment] 2022-10-07 14:32
Hi, 
> Unless you got one of the early ones where AVX-512 still work(ed)?

Sorry, could you please explain this a bit more? I pull the master branch, build it again and run the simple code snippets above with
` clang++ -O3 -Ihighway vmulinttest.cpp ` directly and I got the same linked error as in the issue and same print info.

> For the macro name error, it seems to be coming from the command line. Do you have any -D arguments to the compiler? If not, can you share the command line used?

I am sorry for my expression first. This is the error thrown when I build another project with highway now. I add dependency in this meson [file](https://github.com/JunpengGao233/LoopModels/blob/207d781ed9e1bf0fc20f0b667b980755c81374b1/meson.build#L22-L25)

**Comment by jan-wassenberg** [comment] 2022-10-11 06:55
Hi, I think this is the remaining problem: you build the test program and are surprised it does not use AVX-512.

I believe the cause is the CPU itself. In early Alder Lake steppings, AVX-512 was still enabled. Now, the CPU and/or BIOS disables AVX-512, so Highway is not able to use it.

Does this make sense?

**Comment by jan-wassenberg** [comment] 2022-10-12 14:19
Glad to hear it works. We're happy to add documentation, what exactly would you like to see?

For starters, we are updating the example linked from readme.md to include the `HWY_DYNAMIC_DISPATCH` part. I also recommend copying the skeleton code in `examples/`.

**Comment by JunpengGao233** [comment] 2022-10-12 14:56
Yeah, `examples` and `sort` help a lot to me. It would be very helpful if the suggested style could have updates too. For example, I see in quick reference, it says

> SIMD implementations must be preceded and followed by the following:

But my vectorized operators only defined in one or two files and a lot of other files include them. Should I add `namespace` to all of them? When I would like to refer to some other projects in README.md. Some large projects used highway not following the style exactly. Besides, 
> Additionally, each function that calls Highway ops must either be prefixed with HWY_ATTR, OR reside between HWY_BEFORE_NAMESPACE() and HWY_AFTER_NAMESPACE(). Lambda functions currently require HWY_ATTR before their opening brace.

Do the ops here refer to all the highway operators including `Load` and `Store` and so on? I see the lambda function is added `HWY_ATTR`  in examples. If I do not want to add `namespace` to each file, do I need to add `HWY_ATTR` in each function that I call something like `hn::`.

Sorry that if some may be a newbie way and maybe only confuse me.

**Comment by jan-wassenberg** [comment] 2022-10-17 08:39
Thanks @JunpengGao233 for suggesting these clarifications :)

> Some large projects used highway not following the style exactly.

Yes, that's true. In particular, some of the JPEG XL code was written before we learned some of the lessons required to support SVE. Do you have any other examples?

> Do the ops here refer to all the highway operators including Load and Store and so on?

Yes, I'm updating the readme to mention Load as an example.

> If I do not want to add namespace to each file, do I need to add HWY_ATTR in each function that I call something like hn::.

That's right. Small clarification: BEFORE_NAMESPACE includes some pragmas which avoid the need for HWY_ATTR. That has nothing to do with the namespace, except that there is a compiler bug/limitation which requires the pragma to come before a namespace.

If using static dispatch, you can remove HWY_NAMESPACE and BEFORE_NAMESPACE, and just add HWY_ATTR before every function.

> And it would also be helpful to explain a little about including guards when doing dynamic architecture dispatch. Do we only need to include foreach_target.h in cpp file? 
> And in the included header file, we only need to add the inlcude guard and include highway.h?

That's right, I've added a paragraph to the readme. Hope this helps? Please let us know if you'd suggest any other clarifications.

**Comment by jan-wassenberg** [comment] 2022-10-18 10:35
Closing, please feel free to reopen if you'd like any further changes/clarifications :)

**Closed by jan-wassenberg** 2022-10-18 10:35 UTC
