### ISSUE TITLE
s390x / Big Endian test failures

### ISSUE THREAD

**Issue by eclipseo** [google/highway#775] opened 2022-06-18 16:04 UTC
Hi,

Big Endian problem again I suppose. 3 tests are failing:
(version 0.17)

```
Test  #94: HwyDemoteTestGroup/HwyDemoteTest.TestAllReorderDemote2To/Emu128  # GetParam() = 268435456 ....................Subprocess aborted***Exception:   0.21 sec
Running main() from /builddir/build/BUILD/googletest-release-1.11.0/googletest/src/gtest_main.cc
Note: Google Test filter = HwyDemoteTestGroup/HwyDemoteTest.TestAllReorderDemote2To/Emu128
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from HwyDemoteTestGroup/HwyDemoteTest
[ RUN      ] HwyDemoteTestGroup/HwyDemoteTest.TestAllReorderDemote2To/Emu128
Abort at /builddir/build/BUILD/highway-0.17.0/hwy/tests/demote_test.cc:241: Assert sum_actual - 1E-4 <= sum_actual && sum_expected <= sum_actual + 1E-4
```

```
Test #141: HwyMulTestGroup/HwyMulTest.TestAllReorderWidenMulAccumulate/Emu128  # GetParam() = 268435456 .................Subprocess aborted***Exception:   0.08 sec
Running main() from /builddir/build/BUILD/googletest-release-1.11.0/googletest/src/gtest_main.cc
Note: Google Test filter = HwyMulTestGroup/HwyMulTest.TestAllReorderWidenMulAccumulate/Emu128
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from HwyMulTestGroup/HwyMulTest
[ RUN      ] HwyMulTestGroup/HwyMulTest.TestAllReorderWidenMulAccumulate/Emu128
Abort at /builddir/build/BUILD/highway-0.17.0/hwy/tests/mul_test.cc:388: Emu128, f32x1 lane 0 mismatch: expected '1', got '0'.
```

```
Test #157: DotTestGroup/DotTest.TestAllDotBF16/Emu128  # GetParam() = 268435456 .........................................Subprocess aborted***Exception:   0.07 sec
Running main() from /builddir/build/BUILD/googletest-release-1.11.0/googletest/src/gtest_main.cc
Note: Google Test filter = DotTestGroup/DotTest.TestAllDotBF16/Emu128
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from DotTestGroup/DotTest
[ RUN      ] DotTestGroup/DotTest.TestAllDotBF16/Emu128
Abort at /builddir/build/BUILD/highway-0.17.0/hwy/contrib/dot/dot_test.cc:95: Assert expected - 1E-4 <= actual && actual <= expected + 1E-4
```

s390x is a bit exotic I suppose but it is one of the target of my distribution, and I'd rather not exclude it for all the dependent packages.

Any idea what could be done for this?

Thanks

**Comment by malaterre** [comment] 2022-06-22 06:38
I am also seeing a regression in 0.17 (vs 0.16) on arm64/armhf/s390x/powerpc/ppc64/sparc64. So all big-endian arch have a test suite failure:

* https://buildd.debian.org/status/package.php?p=highway

**Comment by jan-wassenberg** [comment] 2022-06-27 07:08
The fact that all big-endian platforms have a failure is indeed strong evidence, thanks. I've had another careful look at all emu_128 functions relating to bfloat16_t. They do not involve type-punning pointers, the base.h BF16* functions are all implemented by shifting u32 values instead of anything endian-specific, and casts use CopyBytes which boils down to __builtin_memcpy.
Because static analysis hasn't shown the problem, can you help share the output of the following code to be inserted before the HWY_ASSERT in demote_test.cc:241?
```
      fprintf(stderr, "lanes32 %zu i %zu u16 temp %d sum exp %f actual %f\n", N,
              i, temp16[i].bits, sum_expected, sum_actual);
      const RebindToUnsigned<decltype(dbf16)> du16;
      const RebindToUnsigned<decltype(dbf16_half)> du16_half;
      Print(d32, "in0", f0, 0, N);
      Print(d32, "in1", f1, 0, N);
      Print(du16, "v16", BitCast(du16, v16), 0, 2 * N);
      Print(du16_half, "load0",
            BitCast(du16_half, Load(dbf16_half, temp16.get() + 0)), 0, 2 * N);
      Print(du16_half, "load1",
            BitCast(du16_half, Load(dbf16_half, temp16.get() + N)), 0, 2 * N);
      Print(d32, "promoted0", promoted0, 0, N);
      Print(d32, "promoted1", promoted1, 0, N);
```

**Comment by malaterre** [comment] 2022-06-27 08:28
Here is what I see:

```
 94/164 Test  #94: HwyDemoteTestGroup/HwyDemoteTest.TestAllReorderDemote2To/Emu128  # GetParam() = 268435456 ....................Subprocess aborted***Exception:   0.01 sec
Running main() from ./googletest/src/gtest_main.cc
Note: Google Test filter = HwyDemoteTestGroup/HwyDemoteTest.TestAllReorderDemote2To/Emu128
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from HwyDemoteTestGroup/HwyDemoteTest
[ RUN      ] HwyDemoteTestGroup/HwyDemoteTest.TestAllReorderDemote2To/Emu128
lanes32 4 i 0 u16 temp 0 sum exp 0.000000 actual -28.000000
f32x4 in0 [0+ ->]:
  1,-1,0,-0,
f32x4 in1 [0+ ->]:
  0.25,-0.25,4,-32,
u16x8 v16 [0+ ->]:
  0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,
u16x4 load0 [0+ ->]:
  0x0000,0x0000,0x0000,0x0000,
u16x4 load1 [0+ ->]:
  0x0000,0x0000,0x0000,0x0000,
f32x4 promoted0 [0+ ->]:
  0,0,0,0,
f32x4 promoted1 [0+ ->]:
  0,0,0,0,
Abort at ./hwy/tests/demote_test.cc:254: Assert sum_actual - 1E-4 <= sum_actual && sum_expected <= sum_actual + 1E-4

        Start  95: HwyDemoteTestGroup/HwyDemoteTest.TestAllI32F64/Emu128  # GetParam() = 268435456
```

**Comment by jan-wassenberg** [comment] 2022-06-27 11:15
@malaterre Thank you, that's very helpful. I think I see the problem - it's the use of OddEven. We want the upper half, not the odd-indexed lane. Can you confirm this patch fixes it?

**Comment by malaterre** [comment] 2022-06-28 06:33
All unit-tests are now passing on all big-endian arches:

* https://buildd.debian.org/status/package.php?p=highway

**Comment by jan-wassenberg** [comment] 2022-06-28 07:10
Excellent, thanks for re-testing :) Marking as closed.

**Closed by jan-wassenberg** 2022-06-28 07:10 UTC
