### ISSUE TITLE
Issue when SVE2 specified as available (GCC-only)

### ISSUE THREAD

**Issue by benjaminmordaunt** [google/highway#1742] opened 2023-09-12 18:35 UTC
I am compiling the following, which was given in the FAQ as a GodBolt example:

```
#include <hwy/highway.h>
namespace hn = hwy::HWY_NAMESPACE;

using T = float;

void MulAddLoop(const T* HWY_RESTRICT mul_array,
                const T* HWY_RESTRICT add_array,
                const size_t size, T* HWY_RESTRICT x_array) {
  const hn::ScalableTag<T> d;
  for (size_t i = 0; i < size; i += hn::Lanes(d)) {
    const auto mul = hn::Load(d, mul_array + i);
    const auto add = hn::Load(d, add_array + i);
    auto x = hn::Load(d, x_array + i);
    x = hn::MulAdd(mul, x, add);
    hn::Store(x, d, x_array + i);
  }
}
```

When compiled with ARM64 gcc 13.2.0 with the following flags, I receive the following error:

Flags: -O2 -std=c++11 -march=armv8-a+sve2
-----
```
In file included from /opt/compiler-explorer/libs/highway/trunk/hwy/highway.h:418,
                 from <source>:16:
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h: In function 'void MulAddLoop(const T*, const T*, size_t, T*)':
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:1240:31: error: inlining failed in call to 'always_inline' 'svfloat32_t hwy::N_SVE2::Load(Simd<float, N, kPow2>, const hwy::float32_t*) [with long unsigned int N = 64; int kPow2 = 0]': target specific option mismatch
 1240 | HWY_SVE_FOREACH(HWY_SVE_LOAD, Load, ld1)
      |                               ^~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:1195:7: note: in definition of macro 'HWY_SVE_LOAD'
 1195 |       NAME(HWY_SVE_D(BASE, BITS, N, kPow2) d,                    \
      |       ^~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:103:3: note: in expansion of macro 'HWY_SVE_FOREACH_F32'
  103 |   HWY_SVE_FOREACH_F32(X_MACRO, NAME, OP)     \
      |   ^~~~~~~~~~~~~~~~~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:141:3: note: in expansion of macro 'HWY_SVE_FOREACH_F'
  141 |   HWY_SVE_FOREACH_F(X_MACRO, NAME, OP)
      |   ^~~~~~~~~~~~~~~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:1240:1: note: in expansion of macro 'HWY_SVE_FOREACH'
 1240 | HWY_SVE_FOREACH(HWY_SVE_LOAD, Load, ld1)
      | ^~~~~~~~~~~~~~~
<source>:26:30: note: called from here
   26 |     const auto mul = hn::Load(d, mul_array + i);
      |                      ~~~~~~~~^~~~~~~~~~~~~~~~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:1240:31: error: inlining failed in call to 'always_inline' 'svfloat32_t hwy::N_SVE2::Load(Simd<float, N, kPow2>, const hwy::float32_t*) [with long unsigned int N = 64; int kPow2 = 0]': target specific option mismatch
 1240 | HWY_SVE_FOREACH(HWY_SVE_LOAD, Load, ld1)
      |                               ^~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:1195:7: note: in definition of macro 'HWY_SVE_LOAD'
 1195 |       NAME(HWY_SVE_D(BASE, BITS, N, kPow2) d,                    \
      |       ^~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:103:3: note: in expansion of macro 'HWY_SVE_FOREACH_F32'
  103 |   HWY_SVE_FOREACH_F32(X_MACRO, NAME, OP)     \
      |   ^~~~~~~~~~~~~~~~~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:141:3: note: in expansion of macro 'HWY_SVE_FOREACH_F'
  141 |   HWY_SVE_FOREACH_F(X_MACRO, NAME, OP)
      |   ^~~~~~~~~~~~~~~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:1240:1: note: in expansion of macro 'HWY_SVE_FOREACH'
 1240 | HWY_SVE_FOREACH(HWY_SVE_LOAD, Load, ld1)
      | ^~~~~~~~~~~~~~~
<source>:27:30: note: called from here
   27 |     const auto add = hn::Load(d, add_array + i);
      |                      ~~~~~~~~^~~~~~~~~~~~~~~~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:1240:31: error: inlining failed in call to 'always_inline' 'svfloat32_t hwy::N_SVE2::Load(Simd<float, N, kPow2>, const hwy::float32_t*) [with long unsigned int N = 64; int kPow2 = 0]': target specific option mismatch
 1240 | HWY_SVE_FOREACH(HWY_SVE_LOAD, Load, ld1)
      |                               ^~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:1195:7: note: in definition of macro 'HWY_SVE_LOAD'
 1195 |       NAME(HWY_SVE_D(BASE, BITS, N, kPow2) d,                    \
      |       ^~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:103:3: note: in expansion of macro 'HWY_SVE_FOREACH_F32'
  103 |   HWY_SVE_FOREACH_F32(X_MACRO, NAME, OP)     \
      |   ^~~~~~~~~~~~~~~~~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:141:3: note: in expansion of macro 'HWY_SVE_FOREACH_F'
  141 |   HWY_SVE_FOREACH_F(X_MACRO, NAME, OP)
      |   ^~~~~~~~~~~~~~~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:1240:1: note: in expansion of macro 'HWY_SVE_FOREACH'
 1240 | HWY_SVE_FOREACH(HWY_SVE_LOAD, Load, ld1)
      | ^~~~~~~~~~~~~~~
<source>:28:22: note: called from here
   28 |     auto x = hn::Load(d, x_array + i);
      |              ~~~~~~~~^~~~~~~~~~~~~~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:1242:32: error: inlining failed in call to 'always_inline' 'void hwy::N_SVE2::Store(svfloat32_t, Simd<float, N, kPow2>, hwy::float32_t*) [with long unsigned int N = 64; int kPow2 = 0]': target specific option mismatch
 1242 | HWY_SVE_FOREACH(HWY_SVE_STORE, Store, st1)
      |                                ^~~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:1224:16: note: in definition of macro 'HWY_SVE_STORE'
 1224 |   HWY_API void NAME(HWY_SVE_V(BASE, BITS) v,                                \
      |                ^~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:103:3: note: in expansion of macro 'HWY_SVE_FOREACH_F32'
  103 |   HWY_SVE_FOREACH_F32(X_MACRO, NAME, OP)     \
      |   ^~~~~~~~~~~~~~~~~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:141:3: note: in expansion of macro 'HWY_SVE_FOREACH_F'
  141 |   HWY_SVE_FOREACH_F(X_MACRO, NAME, OP)
      |   ^~~~~~~~~~~~~~~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:1242:1: note: in expansion of macro 'HWY_SVE_FOREACH'
 1242 | HWY_SVE_FOREACH(HWY_SVE_STORE, Store, st1)
      | ^~~~~~~~~~~~~~~
<source>:30:14: note: called from here
   30 |     hn::Store(x, d, x_array + i);
      |     ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:872:30: error: inlining failed in call to 'always_inline' 'svfloat32_t hwy::N_SVE2::MulAdd(svfloat32_t, svfloat32_t, svfloat32_t)': target specific option mismatch
  872 | HWY_SVE_FOREACH(HWY_SVE_FMA, MulAdd, mad)
      |                              ^~~~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:867:7: note: in definition of macro 'HWY_SVE_FMA'
  867 |       NAME(HWY_SVE_V(BASE, BITS) mul, HWY_SVE_V(BASE, BITS) x,          \
      |       ^~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:103:3: note: in expansion of macro 'HWY_SVE_FOREACH_F32'
  103 |   HWY_SVE_FOREACH_F32(X_MACRO, NAME, OP)     \
      |   ^~~~~~~~~~~~~~~~~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:141:3: note: in expansion of macro 'HWY_SVE_FOREACH_F'
  141 |   HWY_SVE_FOREACH_F(X_MACRO, NAME, OP)
      |   ^~~~~~~~~~~~~~~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:872:1: note: in expansion of macro 'HWY_SVE_FOREACH'
  872 | HWY_SVE_FOREACH(HWY_SVE_FMA, MulAdd, mad)
      | ^~~~~~~~~~~~~~~
<source>:29:19: note: called from here
   29 |     x = hn::MulAdd(mul, x, add);
      |         ~~~~~~~~~~^~~~~~~~~~~~~
/opt/compiler-explorer/libs/highway/trunk/hwy/ops/arm_sve-inl.h:244:16: error: inlining failed in call to 'always_inline' 'size_t hwy::N_SVE2::Lanes(Simd<T, N, kPow2>) [with T = float; long unsigned int N = 64; int kPow2 = 0]': target specific option mismatch
  244 | HWY_API size_t Lanes(Simd<T, N, kPow2> d) {
      |                ^~~~~
<source>:25:46: note: called from here
   25 |   for (size_t i = 0; i < size; i += hn::Lanes(d)) {
      |                                     ~~~~~~~~~^~~
Compiler returned: 1
```

... but when just specifying SVE, it is OK:

Flags: -O2 -std=c++11 -march=armv8-a+sve
-----
```
MulAddLoop(float const*, float const*, unsigned long, float*):
        cbz     x2, .L1
        mov     x4, 0
        cntw    x5
        ptrue   p0.b, all
.L3:
        ld1w    z0.s, p0/z, [x3, x4, lsl 2]
        ld1w    z1.s, p0/z, [x0, x4, lsl 2]
        ld1w    z2.s, p0/z, [x1, x4, lsl 2]
        fmad    z0.s, p0/m, z1.s, z2.s
        st1w    z0.s, p0, [x3, x4, lsl 2]
        add     x4, x4, x5
        cmp     x2, x4
        bhi     .L3
.L1:
        ret
```

This issue only seems to occur when using GCC. Using the same flags, armv8-a clang 16.0.0 can handle it just fine.

**Comment by jan-wassenberg** [comment] 2023-09-13 09:24
Hi, thanks for the detailed report.
I issue is that our "SVE2" target requires both SVE2 and SVE-AES. Changing to -march=armv8-a+sve2-aes will fix the problem.

However, the fact that you are running into this error means we have a bug: we are attempting to use SVE2 after only checking for SVE2, not AES. Will be fixed shortly :)

**Comment by ag01** [comment] 2023-09-13 10:18
> Hi, thanks for the detailed report. I issue is that our "SVE2" target requires both SVE2 and SVE-AES. Changing to -march=armv8-a+sve2-aes will fix the problem.
> 
> However, the fact that you are running into this error means we have a bug: we are attempting to use SVE2 after only checking for SVE2, not AES. Will be fixed shortly :)

Interesting - I noticed that in the godbolt example, if the function is marked with HWY_ATTR it compiles with -O2 -std=c++11 -march=armv8-a+sve2, e.g: https://godbolt.org/z/vKv3jb9d8

**Comment by jan-wassenberg** [comment] 2023-09-13 10:34
That makes sense :) The issue is the mismatch between the pragma (sve2+aes) and the command line -march=+sve2. I'm changing our code to tolerate that: set sve2 without aes in the pragma if the baseline is +sve2 without aes.

**Comment by jan-wassenberg** [comment] 2023-09-13 10:39
One other thing I noticed while testing: `-march=armv8-a+sve2` causes NEON to fail with the same inlining/target mismatch error on f16 intrinsics.
Somehow `-march=armv8.2-a+sve2` is required. I find that difficult to understand, because the [defaults](https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html) for 8.1 and 8.2 do not seem to involve anything NEON/fp16 related.

**Closed** 2023-09-13 11:17 UTC
